### ISSUE TITLE
How can i get the final tour from a case of TSP?

### ISSUE THREAD

**Issue by small-Qing** [yining043/VRP-DACT#2]
I want to draw a result graph for a TSP case, but I don't know how to output the specific tour.
if i want to get the tour under the pretrained model "tsp20-epoch-199.pt", how can i modify the run.py or other files?

**Comment by yining043** [comment]
Hello, thank you for your interest in our work!!

The best tour is recorded by the "best_solution" variable in the file ./agent/ppo.py  (defined in line 175 and updated in line 203). 

Currently, I do not have existing code to draw graphs for a specific tour, but I am considering creating a Jupyter Notebook to illustrate how to play with DACT (may need some time to update). If you are urgent, you may modify the code in file ./agent/ppo.py or file ./agent/utils.py (this file contains code to call function rollout) in order to store this variable. 

Do note that here all solutions are encoded by the "linked list" data structure, so you have to use the function "get_real_seq(solutions)" defined in line 272 of problems/problem_tsp.py to decode the solution. As mentioned in the readme:

> Please note that in our implementation, the VRP solution is stored in a linked list format. Let us consider a TSP-20 solution [ 6 -> 17 -> 3 -> 9 -> 16 -> 4 -> 12 -> 0 -> 1 -> 5 -> 13 -> 19 -> 11 -> 18 -> 8 -> 14 -> 15 -> 7 -> 2 -> 10 -> 6], we would store this solution as rec = torch.tensor([[ 1, 5, 10, 9, 12, 13, 17, 2, 14, 16, 6, 18, 0, 19, 15, 7, 4, 3,8, 11]]),. Here, if rec[i] = j, it means the node i is connected to node j, i.e., edge i-j is in the solution. For example, edge 0-1, edge 1-5, edge 2-10 are in the solution, so we have rec[0]=1, rec[1]=5 and rec[2]=10.

**Comment by yzhang-gh** [comment]
> Do note that here all solutions are encoded by the "linked list" data structure, so you have to use the function "get_real_seq(solutions)" defined in line 272 of problems/problem_tsp.py to decode the solution. As mentioned in the readme:

That's it 🤕

(Anyway, thanks for your code!)

**Comment by yining043** [comment]
Hi all,

I have provided a Jupyter notebook to help you get started and understand our code. Please open the [Jupyter notebook](https://github.com/yining043/VRP-DACT/blob/main/Play_with_DACT.ipynb) here. Hope this helps :)

**Comment by yining043** [comment]
> I want to draw a result graph for a TSP case, but I don't know how to output the specific tour. if i want to get the tour under the pretrained model "tsp20-epoch-199.pt", how can i modify the run.py or other files?

Hi, I have provided the code to plot the TSP solution, please see the [Jupyter notebook](https://github.com/yining043/VRP-DACT/blob/main/Play_with_DACT.ipynb) here. Hope this helps :)
