### ISSUE TITLE
How can i train my own data?

### ISSUE THREAD

**Issue by Simon9909** [yining043/VRP-DACT#3]
Hello there, thank you for your work. I am very interested in this, and want to train my data.
I'm a beginer in machine learning.
How can i train my own data, and what is the format of the data?
Looking forward to your reply.
想请教您，如何训练我自己的数据，并且数据的格式是什么要求。

**Comment by yining043** [comment]
Thanks for your interest in our work.

Generally, the data format used in our code follows the [wouterkool/attention-learn-to-route](https://github.com/wouterkool/attention-learn-to-route/blob/master/generate_data.py).

More specific to our code:
- For TSP, the dataset class TSPDataset is defined in line 240 of file problems/problem_tsp.py. The object of this class will have a self.data variable that is a python list storing each TSP instance, where the coordinates of N nodes in each instance are stored in a python dict that has a key ’coordinates‘ with its values being the coordinates of nodes 1,....,N, respectively.
- For CVRP,  the dataset class CVRPDataset is defined in line 383 of file problems/problem_vrp.py. Similarly, all instances are stored in the self.data variable. For each instance self.data[i], it is represented by a dict, which has a key-value pair 'coordinates' storing the coordinate of each node and another key-value pair  'demand' storing the demand of each node. Here, the demand is normalised by the 'capacity' to be within range [0,1]. We use the first node with index 0 to represent the depot and the other N nodes to store the customer nodes. Since we consider dummy depots, so after loading data from the '.pkl', we will process the instance to include several dummy depots through make_instance function. Specifically, the function will duplicate the depots multiple times according to the dummy_rate. Taking CVRP-20 as an example, where we consider 10 dummy nodes (dummy rate = 10/20 = 0.5), both key-value pair  'coordinates' and 'demand' (i.e., instance self.data[i]) will use index from 0-9 to store 10 (repeated) depots and then use index from 10-29 to store 20 customer nodes.

**Comment by Simon9909** [comment]
Thank you very much for your reply!
Now i've trained my data and got ‘epoch-199.pt’. I'm wondering if i can get the tour of the result of CVRP, and make it shown.
Looking forward to your reply and hope you have a good day!

**Comment by Simon9909** [comment]
Thank you very much for your reply!
Now i've trained my data and got ‘epoch-199.pt’. I'm wondering if i can get the tour of the result of CVRP, and make it shown.
Looking forward to your reply and hope you have a good day!

**Comment by yining043** [comment]
Hi, you can refer to our [NoteBook](https://github.com/yining043/VRP-DACT/blob/main/Play_with_DACT.ipynb) for an example of getting the tours and making it shown for TSP. For CVRP, it is similar and you may only need to note that the nodes at the beginning of rec variable are dummy depots as mentioned in the above reply.

**Comment by Simon9909** [comment]
Thank you for your patient reply!
Your jupyter notebook helps me a lot!
Wish you all good and have a nice day~
