### ISSUE TITLE
About learning curves

### ISSUE THREAD

**Issue by yzhang-gh** [yining043/VRP-DACT#4]
Thanks for your paper and code.

When I train DACT (for TSP), the loss occasionally goes wild (although it doesn't affect the final result). I was wondering whether it is as expected? Or maybe I did something wrong?

![image](https://user-images.githubusercontent.com/7588612/172336392-a0db048a-8890-4d7a-ab76-26f8ea2b8fae.png)

![image](https://user-images.githubusercontent.com/7588612/172338152-dd02cd46-b5f5-43ad-924e-c9225d5d7ac4.png)

I used `max_grad_norm = 0.1` for TSP 100 (I have seen it is `--max_grad_norm 0.2` for TSP 50 from the `README`)

**Comment by yining043** [comment]
Hi, thank you for the question!

If the final results are good, no worries, this is not a problem. Anyway, I also encountered this before (it may come unpredictably some time for TSP but may not come for CVRP). I think this might because of the critic. Actually, in our new work [N2S](https://github.com/yining043/PDP-N2S), we use a new critic which also takes the current best cost found so far as an additional input, leading to better stability (see code [here](https://github.com/yining043/PDP-N2S/blob/main/nets/critic_network.py)).

**Comment by yzhang-gh** [comment]
Thank you for the reply!
