### ISSUE TITLE
The inference time

### ISSUE THREAD

**Issue by yzhang-gh** [yining043/VRP-DACT#5]
Hi, it's me again ;)

When I run the following command to inference on TSP 50 problems (on _a single TITAN RTX GPU card_, 24G memory),

```
python run.py --graph_size 50 --eval_only --load_path pretrained/tsp50-epoch-198.pt --T_max 5000 \
              --val_size 10000 --val_dataset datasets/tsp_50_10000.pkl --val_m 1 --no_tb --no_saving --no_DDP
```

it requires 30 minutes to finish

```
 'val_dataset': 'datasets/tsp_50_10000.pkl',
 'val_m': 1,
 'val_size': 10000,
 'world_size': 1}
TSP with 50 nodes.  Do assert: False
{'Total': 280801, 'Trainable': 280801}
Distributed: False
 [*] Loading data from pretrained/tsp50-epoch-198.pt

Inference with x1 augments...
10000 instances initialized.
rollout:   1%|▏                   | 58/5000 [00:21<30:37,  2.69it/s]
```

(The rollout progress is smooth and there doesn't seem to exist any bottleneck.)

For TSP 100, I need to reduce the batch size, for example, to 4096. And the time for the rollout of a batch becomes 40 minutes.

According to the paper, they should be 6 and 18 minutes respectively (for one GPU and 512 batch size). As far as I can see, the GPU used for the paper is also TITAN RTX. Are there any other techniques used to speed up the inference?

**Comment by yining043** [comment]
Hi, thanks for the questions!

According to the paper, 'For DACT, we report the time for inferring all 10,000 instances with multiple GPU cards in “()", and a small batch (512 instances) with one single GPU card in “{}"'

So you can speed up by using multiple GPU cards (e.g., 4 or 8) to solve 10,000 instances in parallel. You can change the command to:

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python run.py ...... (but remove '--no_DDP' since we are using [Distributed Data Parallel](https://pytorch.org/docs/stable/notes/ddp.html) in our code for speed up)

Also, the CPU model may also affect the time needed based on my experience.

**Comment by yzhang-gh** [comment]
Thanks for the reply!

However, it looks like the time in `{}` is even smaller than that in `()` 😂

```
TSP                                    N=50                N=100
DACT (T=5k) 3.83 0.00% {32s}(2m) 5.70 0.02% {2m}(6m) 7.81 0.61% {4m}(18m)
```

The issue is even though I'm using the same single GPU (and larger batch size), the time is much longer (30m >> 6m) ...

**Comment by yining043** [comment]
Hi, oh I might see the confusion. Here, the time in {} is to solve 512 instances only (with one single card), instead of solving all 10,000 instances. And the time in () is to solve all 10,000 instances with multiple GPUs. Unlike construction solvers, improvement solvers require more computational resources. And I think it is an interesting future research direction to improve this limitation.

**Comment by yining043** [comment]
And you are right, larger batch sizes require more time. I think this should be the case, since more tensor computation are required to be performed on the single card when the batch size is larger.

**Comment by yzhang-gh** [comment]
> Hi, oh I might see the confusion. Here, the time in {} is to solve 512 instances only (with one single card), instead of solving all 10,000 instances.

Ah, I see. Thanks.
