### ISSUE TITLE
Some questions about CPEs in codes

### ISSUE THREAD

**Issue by small-Qing** [yining043/VRP-DACT#6]
Hi, I have some questions about CPEs in codes（nets/graph_layers.py/EmbeddingNet/Cyclic_Positional_Encoding）

```
skip_base = np.power(n_position, 1 / (emb_dim // 2))
skip_set = np.linspace(skip_base, n_position, emb_dim // 2, dtype = 'int')
```

I assume that the `skip_set` is `wavelength` within the range $[N^{\frac{1}{d/2}}, N]$, and the `skip`  is  $ω_d$.
Then you iterate d times but only partition out d/2 units in the range. Could you explain the logic in the formulation?

```
for i in range(emb_dim):
            # see Appendix B
            skip = skip_set[i //3 * 3 + 1] if  (i //3 * 3 + 1) < (emb_dim // 2) else skip_set[-1]
```

In addition, Could you explain the notation in papers about `fai` in codes? I will appreciate it if you could reply me! Thanks :)

```
# see Appendix B
fai = 0 if i <= (emb_dim // 2) else  2 * np.pi * ((-i + (emb_dim // 2)) / (emb_dim // 2))
```

**Comment by yining043** [comment]
Hi thanks for the question!

The wavelength is getting lager and lager. If we look at the visualisation in Figure 5(a), you'll see that the same wavelength is repeated several times. And the last half all use the largest wavelength N. 

As mentioned in the appendix, "Empirically, we fix the last half of the angular frequencies to N (the largest value) to better preserve the desired cyclic and adjacency similarity properties."

For the fai, it is something not that important. I choose this design because personally I feel that a diversified phi makes the final half more diverse in some sense which may help the model learn more powerful representations (but seems like not important from the results:)).

**Comment by small-Qing** [comment]
Ok, i see. In my opinion, although you iterate emb_dim times, you just need to calculate the iterations which meet the condition: d<emb_dim//2, so you only partition out emb_dim/2 units in the range for calculations.  
And ,the `fai` just seems to be the bias to vary solutions.
However, when i start to understand your codes about CPEs, i think the `skip` is the wavelength, but the Eq.(13) in your paper which has the same meaning in code: `skip = skip_set[i//3 * 3 + 1] if  (i//3 * 3 + 1)<(emb_dim//2) else skip_set[-1]` , that is indicating the `skip` is the $\omega_d$. 
Maybe i just misunderstand your code :(  All in all, could you certain my hypothesis：skip=wavelength?

**Comment by yining043** [comment]
Sorry for the confusion.

The skip is the wavelength and I think there might be a typo in the appendix.
Thank you for pointing out this issue.
