### ISSUE TITLE
Clarification needed on post and pre computation in code

### ISSUE THREAD

**Issue by Visterainer** [yining043/VRP-DACT#9]
Hello,

I've come across this segment of code and I'm trying to understand its intent and functionality:
`
argsort = solution.argsort()  
loc = x_in[:, :, :2] 
post = loc.gather(1, solution.view(bs, -1, 1).expand_as(loc))
pre = loc.gather(1, argsort.view(bs, -1, 1).expand_as(loc))
post = torch.norm(post - loc, 2, -1, True)
pre = torch.norm(pre - loc, 2, -1, True)
`
What's post and pre means?
I try get it as a next point and last point of current point....
From the comments and variable names, it seems the goal is to compute the coordinates of the next (post) and previous (pre) nodes for each node based on the given solution. However, based on the behavior of loc.gather(...), it seems the current implementation does not achieve this. Instead, it looks like it's rearranging the nodes based on the solution order.

**Comment by yining043** [comment]
Hi Visterainer,

Thanks for your question. You are correct that the goal is to compute the coordinates of the next (post) and previous (pre) nodes for each node based on the given solution. We can achieve this by rearranging the nodes because the solution variable "solution" encodes the order information in a linked list format. If solution[i] = j it means that node j is the next node of node i (also node i is the previous node of node j). Thus rearranging the solution can compute the difference between the coordinates of the pair (a node, the next node) and the pair (a node, the previous node) during "post - loc" and "pre - loc".

You may find more info on the linked list format in the readme and the provided jupyter notebook. Thanks!

**Comment by Visterainer** [comment]
Thank you, yining043, for your detailed response. Your explanation was very thorough and cleared up my confusion. I appreciate the time you took to clarify things for me.
